version: '2.1'

services:
  postgres:
    extends:
      file: ../docker-common.yml
      service: postgres
    volumes_from:
      - pgdata

  redis:
    extends:
      file: ../docker-common.yml
      service: redis

  pgdata:
    extends:
      file: ../docker-common.yml
      service: pgdata

  smtp:
    extends:
      file: ../docker-common.yml
      service: smtp

  smart_backend:
    extends:
      file: ../docker-common.yml
      service: smart_backend
    build: ../../backend/
    image: rti/smart-backend:R_0_0_1
    depends_on:
      - postgres
      - redis
      - smtp

  smart_frontend:
    extends:
      file: ../docker-common.yml
      service: smart_frontend
    build: ../../frontend/
    image: rti/smart-frontend:R_0_0_1
    command: node_modules/.bin/webpack --watch

  celery_worker:
    extends:
      file: ../docker-common.yml
      service: celery_worker
    build: ../../backend/
    image: rti/smart-backend:R_0_0_1
    depends_on:
      - postgres
      - redis
      - smart_backend
