version: '2.1'

services:
  postgres:
    image: postgres:9.6.2
    environment:
      - POSTGRES_PASSWORD=my-secret-password
      - POSTGRES_USER=smart
      - POSTGRES_DB=smart

  redis:
    image: redis:3.0

  pgdata:
    image: tianon/true
    volumes:
      - /var/lib/postgresql/data

  samrt_nginx:
    image: nginx:latest
    ports:
      - 80:80
    environment:
      - DOLLAR=$$
    volumes:
      - ../backend/nginx.conf:/etc/nginx/conf.d/nginx.conf.template
      - ../backend/django/static/:/code/static

  smart_backend:
    container_name: smart_backend
    volumes:
      - ../backend/django:/code
      - ../frontend:/code/frontend
    command: ./runserver.sh

  smart_frontend:
    container_name: smart_frontend
    volumes:
      - ../frontend/:/code
      - /code/node_modules

  celery_worker:
    volumes:
      - ../backend/django:/code
    command: celery -A smart worker -l info -n default@%h
